[workspace]
changelog_update = true
semver_check = true
git_tag_enable = true
git_release_enable = true
publish_allow_dirty = false

[[package]]
name = "kbd"
version_group = "kbd"
changelog_path = "CHANGELOG.md"

[[package]]
name = "kbd-crossterm"
version_group = "kbd"
changelog_path = "CHANGELOG.md"

[[package]]
name = "kbd-egui"
version_group = "kbd"
changelog_path = "CHANGELOG.md"

[[package]]
name = "kbd-evdev"
version_group = "kbd"
changelog_path = "CHANGELOG.md"

[[package]]
name = "kbd-global"
version_group = "kbd"
changelog_path = "CHANGELOG.md"

[[package]]
name = "kbd-iced"
version_group = "kbd"
changelog_path = "CHANGELOG.md"

[[package]]
name = "kbd-tao"
version_group = "kbd"
changelog_path = "CHANGELOG.md"

[[package]]
name = "kbd-winit"
version_group = "kbd"
changelog_path = "CHANGELOG.md"

# excluded from releases
[[package]]
name = "kbd-derive"
release = false
publish = false

[[package]]
name = "kbd-portal"
release = false
publish = false

[[package]]
name = "kbd-xkb"
release = false
publish = false

[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project attempts to adhere to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

<!--
## [${version}]

### Added - for new features
### Changed - for changes in existing functionality
### Deprecated - for soon-to-be removed features
### Removed - for now removed features
### Fixed - for any bug fixes
### Security - in case of vulnerabilities

[${version}]: https://github.com/joshuadavidthomas/kbd/releases/tag/${tag}
-->\n
"""
body = """
{% if version -%}
    ## [{{ version | trim_start_matches(pat="v") }}]
{% else -%}
    ## [Unreleased]
{% endif -%}
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {{ commit.message | split(pat="\n") | first | upper_first | trim }}\
    {% endfor %}
{% endfor %}\n
"""
footer = """
{% for release in releases -%}
    {% if release.version -%}
        {% if release.previous.version -%}
            [{{ release.version | trim_start_matches(pat="v") }}]: https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/compare/{{ release.previous.version }}..{{ release.version }}
        {% else -%}
            [{{ release.version | trim_start_matches(pat="v") }}]: https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/tree/{{ release.version }}
        {% endif -%}
    {% else -%}
        [unreleased]: https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/compare/{{ release.previous.version }}..HEAD
    {% endif -%}
{% endfor %}
<!-- generated by git-cliff -->
"""
trim = true
