//! Timing and repeat policies for bindings.
//!
//! These types control how a binding reacts to timing-sensitive events:
//! OS auto-repeat (held keys), rapid re-presses (debounce), and
//! steady-state throughput (rate limiting). They're carried by
//! [`BindingOptions`](crate::binding::BindingOptions) and consumed by
//! the dispatcher and engine at runtime.

use std::time::Duration;

/// How a matched binding handles OS auto-repeat events.
///
/// Repeat events are generated by the kernel when a key is held down.
/// This policy controls whether those repeats re-fire the binding's
/// action — distinct from [debounce](crate::binding::BindingOptions::with_debounce),
/// which suppresses rapid re-presses (release then press again).
///
/// # Examples
///
/// ```
/// use std::time::Duration;
/// use kbd::policy::RepeatPolicy;
///
/// // Default: suppress repeat events
/// let policy = RepeatPolicy::default();
/// assert!(matches!(policy, RepeatPolicy::Suppress));
///
/// // Allow repeats at OS rate
/// let policy = RepeatPolicy::Allow;
///
/// // Custom repeat with delay before first repeat and rate limiting
/// use kbd::policy::RepeatTiming;
/// let policy = RepeatPolicy::Custom(RepeatTiming::new(
///     Duration::from_millis(500),
///     Duration::from_millis(30),
/// ));
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[non_exhaustive]
pub enum RepeatPolicy {
    /// Suppress repeat events — action fires once on press only. Default.
    #[default]
    Suppress,
    /// Allow repeat events to re-fire the action every time the OS
    /// generates a repeat event.
    Allow,
    /// Custom repeat behavior with controlled timing.
    Custom(RepeatTiming),
}

/// Timing parameters for custom repeat behavior.
///
/// `delay` is the time after the initial press before the first repeat
/// fires. `rate` is the minimum interval between subsequent repeat fires.
///
/// # Examples
///
/// ```
/// use std::time::Duration;
/// use kbd::policy::RepeatTiming;
///
/// let timing = RepeatTiming::new(
///     Duration::from_millis(500),
///     Duration::from_millis(30),
/// );
/// assert_eq!(timing.delay(), Duration::from_millis(500));
/// assert_eq!(timing.rate(), Duration::from_millis(30));
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct RepeatTiming {
    delay: Duration,
    rate: Duration,
}

impl RepeatTiming {
    /// Create a new repeat timing configuration.
    ///
    /// `delay` is the time after the initial press before the first
    /// repeat fires. `rate` is the minimum interval between subsequent
    /// repeat fires.
    #[must_use]
    pub const fn new(delay: Duration, rate: Duration) -> Self {
        Self { delay, rate }
    }

    /// Time after initial press before the first repeat fires.
    #[must_use]
    pub const fn delay(&self) -> Duration {
        self.delay
    }

    /// Minimum interval between subsequent repeat fires.
    #[must_use]
    pub const fn rate(&self) -> Duration {
        self.rate
    }
}

/// Rate limit for a binding — caps how many times the action fires
/// within a sliding time window.
///
/// Distinct from [debounce](crate::binding::BindingOptions::with_debounce):
/// debounce suppresses rapid re-presses, rate limiting caps steady-state
/// throughput.
///
/// # Examples
///
/// ```
/// use std::time::Duration;
/// use kbd::policy::RateLimit;
///
/// // At most 5 fires per second
/// let rl = RateLimit::new(5, Duration::from_secs(1));
/// assert_eq!(rl.max_count(), 5);
/// assert_eq!(rl.window(), Duration::from_secs(1));
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct RateLimit {
    max_count: u32,
    window: Duration,
}

impl RateLimit {
    /// Create a new rate limit.
    ///
    /// `max_count` is the maximum number of action fires within `window`.
    #[must_use]
    pub const fn new(max_count: u32, window: Duration) -> Self {
        Self { max_count, window }
    }

    /// Maximum number of action fires within the window.
    #[must_use]
    pub const fn max_count(&self) -> u32 {
        self.max_count
    }

    /// Sliding time window for the rate limit.
    #[must_use]
    pub const fn window(&self) -> Duration {
        self.window
    }
}
