name: deny

on:
  pull_request:
    paths:
      - .github/workflows/deny.yml
      - crates/**
      - deny.toml
      - Cargo.toml
      - Cargo.lock
  push:
    branches: [main]
    paths:
      - .github/workflows/deny.yml
      - crates/**
      - deny.toml
      - Cargo.toml
      - Cargo.lock
  workflow_call:

concurrency:
  group: deny-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  should-run:
    if: "${{ github.event_name != 'push' || !contains(github.event.head_commit.message, ':bookmark: bump version') }}"
    runs-on: ubuntu-latest
    steps:
      - run: true

  deny:
    runs-on: ubuntu-24.04
    needs: [should-run]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: EmbarkStudios/cargo-deny-action@3c6349835b2b7b196a839186cb8b78e02f7b5f25 # v2.1.1
