name: lint

on:
  pull_request:
  push:
    branches: [main]
  workflow_call:

concurrency:
  group: lint-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  should-run:
    if: "${{ github.event_name != 'push' || !contains(github.event.head_commit.message, ':bookmark: bump version') }}"
    runs-on: ubuntu-latest
    steps:
      - run: true

  rust-changes:
    needs: [should-run]
    runs-on: ubuntu-latest
    outputs:
      rust: ${{ steps.filter.outputs.rust }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            rust:
              - '.github/workflows/lint.yml'
              - 'src/**'
              - 'tests/**'
              - 'Cargo.toml'
              - 'Cargo.lock'
              - 'Justfile'

  rustfmt:
    runs-on: ubuntu-24.04
    needs: rust-changes
    if: needs.rust-changes.outputs.rust == 'true'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c
        with:
          toolchain: nightly
          components: rustfmt
          cache: true

      - name: Run rustfmt
        run: cargo +nightly fmt --all -- --check

  clippy:
    runs-on: ubuntu-24.04
    needs: rust-changes
    if: needs.rust-changes.outputs.rust == 'true'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c
        with:
          components: clippy
          cache: true

      - name: Run clippy
        run: cargo clippy --all-targets --all-features --benches -- -D warnings

  lint:
    runs-on: ubuntu-latest
    needs: [rustfmt, clippy]
    if: always()
    steps:
      - name: OK
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Fail
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
